### ISSUE TITLE
batch scoring example

### ISSUE THREAD

**Issue by Meihan-basis** [basisai/examples#8]
1.  missing trained model to start with
2. Provide the link to the trained model in prerequisite, like
## Prerequisites
To start a batch scoring job, you need a trained model which is provided [here](https://bedrock.basis-ai.com/project/view/kokmeng-projects/training/pipeline/view/churn-gcp), click the link to start. 

3. [Documentation](https://docs.basis-ai.com/guides/quickstart/next-step-deploy-a-batch-scoring) is outdated, our current UI is different from what shown here.

**Comment by kesamet** [comment]
1. user must have his **own approved trained model** to start with. the user will be in a different account, and so won't be able to see our projects.
2. see 1)
3. am i missing something? the documentation shows the same interface as the UI. can you paste what you see?

**Comment by Meihan-basis** [comment]
Started from wrong place, so UI looks different, now I know where to start with. Starting a new pipeline to train the model, will create a PR later.
